import { useState } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { useLiveQuery } from 'dexie-react-hooks'
import { v4 as uuid } from 'uuid'
import { TopBar } from '../components/TopBar'
import { db } from '../db/db'
import { useSettingsStore } from '../store/useSettingsStore'
import { chatCompletion } from '../lib/deepseek'
import { employmentPatch } from '../lib/career'

const thresholds={入门:55,普通:65,竞争激烈:75}
export function InterviewPage(){const {jobId}=useParams(),nav=useNavigate(),settings=useSettingsStore();const job=useLiveQuery(()=>jobId?db.jobListings.get(jobId):undefined,[jobId]);const session=useLiveQuery(()=>jobId?db.interviews.where('jobId').equals(jobId).first():undefined,[jobId]);const [input,setInput]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('')
async function call(prompt:string,jsonMode=false){return chatCompletion({apiKey:settings.apiKey,baseUrl:settings.baseUrl,model:settings.model,messages:[{role:'system',content:prompt},{role:'user',content:'请继续'}],jsonMode})}
async function start(){if(!job||!settings.apiKey)return;setBusy(true);try{const active=await db.interviews.where('status').equals('active').first();if(active&&active.jobId!==job.id)throw new Error('请先完成当前进行中的面试');const q=await call(`你是${job.company}的${job.interviewer}，正在面试${job.title}。要求：${job.requirements.join('；')}。这是4轮专业面试，请开场并只问第1个具体专业知识或实际场景问题，不要问泛泛自我介绍。只输出问题。`);const now=Date.now();await db.interviews.add({id:uuid(),jobId:job.id,status:'active',round:0,messages:[{role:'interviewer',content:q.trim(),createdAt:now}],createdAt:now,updatedAt:now});await db.jobListings.update(job.id,{status:'interviewing'})}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
async function answer(){if(!job||!session||!input.trim())return;setBusy(true);const answerText=input.trim();setInput('');const messages=[...session.messages,{role:'candidate' as const,content:answerText,createdAt:Date.now()}];try{const nextRound=session.round+1;if(nextRound<4){const transcript=messages.map(m=>`${m.role==='interviewer'?'面试官':'候选人'}：${m.content}`).join('\n');const q=await call(`你是${job.title}专业面试官。岗位要求：${job.requirements.join('；')}。\n${transcript}\n根据上一回答只提出下一个更深入的专业知识或实际问题。这是第${nextRound+1}/4题，只输出问题。`);messages.push({role:'interviewer',content:q.trim(),createdAt:Date.now()});await db.interviews.update(session.id,{round:nextRound,messages,updatedAt:Date.now()})}else{const raw=await call(`你是严格的${job.title}面试评审。根据记录评分：专业知识0-35、解决能力0-30、表达逻辑0-20、可信度与匹配0-15。只输出JSON {"knowledge":0,"problemSolving":0,"communication":0,"fit":0,"feedback":"简评"}。记录：${messages.map(m=>m.role+':'+m.content).join('\n')}`,true);const p=JSON.parse(raw.match(/```(?:json)?\s*([\s\S]*?)```/i)?.[1]??raw);const score=Math.max(0,Math.min(100,Number(p.knowledge||0)+Number(p.problemSolving||0)+Number(p.communication||0)+Number(p.fit||0)));const passed=score>=thresholds[job.difficulty];await db.interviews.update(session.id,{round:4,messages,status:passed?'passed':'failed',score,scoreBreakdown:p,feedback:String(p.feedback||''),updatedAt:Date.now()});await db.jobListings.update(job.id,{status:passed?'hired':'rejected'});if(passed){const ep=employmentPatch(job.title,job.monthlySalary);settings.setSettings({userOccupation:ep.occupation,userMonthlySalary:ep.monthlySalary,userJobStartedDate:ep.jobStartedDate,userLastSalaryDate:ep.lastSalaryDate})}}}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
if(!job)return null;return <div className="flex h-[var(--app-height)] flex-col overflow-hidden bg-[#ededed]"><TopBar title={`${job.title}面试`} showBack/><div className="flex-1 overflow-y-auto p-4">{!session?<button disabled={busy} onClick={start} className="w-full rounded-xl bg-gray-900 py-3 text-white">{busy?'面试官准备中…':'开始专业面试'}</button>:<>{session.messages.map((m,i)=><div key={i} className={`mb-3 flex ${m.role==='candidate'?'justify-end':''}`}><div className={`max-w-[82%] rounded-2xl px-3 py-2 text-sm ${m.role==='candidate'?'bg-[#95ec69]':'bg-white'}`}>{m.content}</div></div>)}{session.status!=='active'&&<div className="rounded-xl bg-white p-4 text-center"><b className="text-xl">{session.status==='passed'?'录用':'未录用'} · {session.score}分</b><p className="mt-2 text-sm text-gray-500">{session.feedback}</p><button onClick={()=>nav('/work')} className="mt-3 text-sm text-blue-500">返回工作</button></div>}</>}</div>{session?.status==='active'&&<div className="flex gap-2 border-t bg-white p-2"><textarea value={input} onChange={e=>setInput(e.target.value)} className="flex-1 resize-none rounded-xl border px-3 py-2 text-sm" placeholder="回答面试问题"/><button disabled={busy||!input.trim()} onClick={answer} className="rounded-xl bg-gray-900 px-4 text-white disabled:opacity-40">发送</button></div>}{error&&<p className="bg-red-50 p-2 text-xs text-red-500">{error}</p>}</div>}
