import {
  Aperture,
  ArchiveRestore,
  Bell,
  BookOpen,
  Bot,
  Brain,
  BriefcaseBusiness,
  CalendarDays,
  Check,
  CircleAlert,
  CircleDollarSign,
  CircleDot,
  Compass,
  Dice5,
  Download,
  Drama,
  Eye,
  FlaskConical,
  Gift,
  Globe,
  HandCoins,
  Heart,
  Image,
  Leaf,
  LibraryBig,
  Link,
  Map,
  MessageCircleMore,
  MessageSquare,
  Moon,
  Network,
  Package,
  Palette,
  PenLine,
  Puzzle,
  Save,
  Search,
  Settings,
  ShoppingBag,
  Smile,
  Sparkles,
  Sprout,
  Store,
  Target,
  Telescope,
  Users,
  WandSparkles,
  Warehouse,
  Wrench,
  type LucideIcon,
  type LucideProps,
} from 'lucide-react'

const ICONS: Record<string, LucideIcon> = {
  '📖': BookOpen,
  '📦': Package,
  '🧪': FlaskConical,
  '🧭': Compass,
  '💭': MessageCircleMore,
  '🎭': Drama,
  '💕': Heart,
  '🗺️': Map,
  '🔮': Eye,
  '💼': BriefcaseBusiness,
  '🧩': Puzzle,
  '✨': Sparkles,
  '✦': Sparkles,
  '🛠️': Wrench,
  '🎁': Gift,
  '🤖': Bot,
  '📚': LibraryBig,
  '💾': Save,
  '🛍️': ShoppingBag,
  '🔔': Bell,
  '📸': Aperture,
  '🔭': Telescope,
  '◉': CircleDot,
  '⚙': Settings,
  '▦': Puzzle,
  '☺': Smile,
  '🌙': Moon,
  '✍️': PenLine,
  '💬': MessageSquare,
  '🧠': Brain,
  '🌐': Globe,
  '🔎': Search,
  '🎯': Target,
  '🌱': Sprout,
  '🪄': WandSparkles,
  '🌿': Leaf,
  '🎨': Palette,
  check: Check,
  alert: CircleAlert,
  archive: ArchiveRestore,
  calendar: CalendarDays,
  dice: Dice5,
  download: Download,
  finance: CircleDollarSign,
  gift: Gift,
  image: Image,
  link: Link,
  loan: HandCoins,
  shop: Store,
  users: Users,
  warehouse: Warehouse,
  network: Network,
}

export function UiIcon({ name, ...props }: { name: string } & Omit<LucideProps, 'ref'>) {
  const Icon = ICONS[name] ?? CircleDot
  return <Icon aria-hidden="true" strokeWidth={1.8} {...props} />
}
